[tool.black]
line-length = 88
target-version = ['py312']
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["myapp"]
combine_as_imports = true

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503", "B008"]